services:
  playwright-mcp:
    build:
      context: ./containers
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8010:8010"
    command: ["/bin/bash", "-c", "./scripts/xvfb.sh && tail -f /dev/null"]
    volumes:
      - ./images:/app/images
      - ./containers/scripts:/app/scripts
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/health" ]
      interval: 1s
      retries: 30
  client:
    depends_on:
      playwright-mcp:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - node_modules_cache:/app/packages/client/node_modules
      - dist_cache:/app/packages/client/dist
    environment:
      - NODE_ENV=development
    restart: unless-stopped
volumes:
  node_modules_cache:
  dist_cache:
